FROM golang:1.26rc2-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

FROM alpine:latest
RUN apk --no-cache add ca-certificates && \
    addgroup -g 1000 appuser && adduser -u 1000 -D -G appuser appuser
WORKDIR /home/appuser
COPY --from=builder /app/worker .
USER appuser
CMD ["./worker"]
