// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Eval struct {
	ID               int64              `json:"id"`
	SubscriptionID   int64              `json:"subscription_id"`
	GameID           pgtype.Int8        `json:"game_id"`
	EvaluatedAt      pgtype.Timestamptz `json:"evaluated_at"`
	EvalStatus       string             `json:"eval_status"`
	DiscordMessageID pgtype.Text        `json:"discord_message_id"`
}

type Feedback struct {
	ID               int64              `json:"id"`
	DiscordMessageID string             `json:"discord_message_id"`
	FeedbackText     string             `json:"feedback_text"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RiotAccountCache struct {
	ID        int64              `json:"id"`
	GameName  string             `json:"game_name"`
	TagLine   string             `json:"tag_line"`
	Region    string             `json:"region"`
	Puuid     string             `json:"puuid"`
	CachedAt  pgtype.Timestamptz `json:"cached_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type RiotGameCache struct {
	ID           int64              `json:"id"`
	Puuid        string             `json:"puuid"`
	Region       string             `json:"region"`
	InGame       bool               `json:"in_game"`
	GameID       pgtype.Int8        `json:"game_id"`
	Participants []byte             `json:"participants"`
	CachedAt     pgtype.Timestamptz `json:"cached_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type Subscription struct {
	ID               int64              `json:"id"`
	DiscordChannelID string             `json:"discord_channel_id"`
	ServerID         string             `json:"server_id"`
	LolUsername      string             `json:"lol_username"`
	Region           string             `json:"region"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	LastEvaluatedAt  pgtype.Timestamptz `json:"last_evaluated_at"`
}

type Translation struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	Translation string             `json:"translation"`
	Provider    string             `json:"provider"`
	Model       string             `json:"model"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TranslationToEval struct {
	TranslationID int64 `json:"translation_id"`
	EvalID        int64 `json:"eval_id"`
}
