// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Eval struct {
	ID               int64              `json:"id"`
	SubscriptionID   int64              `json:"subscription_id"`
	EvaluatedAt      pgtype.Timestamptz `json:"evaluated_at"`
	EvalStatus       string             `json:"eval_status"`
	DiscordMessageID pgtype.Text        `json:"discord_message_id"`
}

type Feedback struct {
	ID               int64              `json:"id"`
	DiscordMessageID string             `json:"discord_message_id"`
	FeedbackText     string             `json:"feedback_text"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID               int64              `json:"id"`
	DiscordChannelID string             `json:"discord_channel_id"`
	LolUsername      string             `json:"lol_username"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Region           string             `json:"region"`
}

type Translation struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	Translation string             `json:"translation"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TranslationToEval struct {
	TranslationID int64 `json:"translation_id"`
	EvalID        int64 `json:"eval_id"`
}
